spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        properties-exchange:
          destination: propertiesExchange
      rabbit:
        bindings:
          properties-exchange:
            producer:
              routingKeyExpression: '"test.*"'
      default:
        contentType: application/json